### ISSUE TITLE
[Epic] Consolidate both policy types into one view

### ISSUE THREAD

**Issue by jordojordo** [rancher/kubewarden-ui#832]
With the ongoing ux changes we will need to consolidate the ClusterAdmissionPolicies and AdmissionPolicies into one view, this will include changes made to the list, detail, and create/edit views for each resource.

- [ ] #833
- [ ] Consolidate policy list view
- [ ] Consolidate policy detail view
- [ ] Consolidate policy edit config view
- [ ] Update related policies layout in Policy Server to reflect consolidated types
